sudo: required
services:
 - docker

before_install:
 - docker build -t react-docker-frontend -f Dockerfile.dev .

script:
 - docker run -e CI=true react-docker-frontend npm run test

deploy:
 edge: true
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "react-docker-frontend"
 env: "ReactDockerFrontend-env"
 bucket_name: "elasticbeanstalk-us-east-2-886221772239"
 bucket_path: "react-docker-frontend"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
